name: Phan

on: [ push, pull_request ]

jobs:
    phan:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ ubuntu-latest ]
                php: [ '7.3', '7.4', '8.0' ]
                symfony: [ '~4.4', '~5.2' ]
                composer-flags: [ '--prefer-stable --prefer-lowest', '' ]

        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    coverage: none # disable xdebug, pcov
                    extensions: ast

            -   name: Get Composer Cache Directory
                id: composer-cache
                run: |
                    echo "::set-output name=dir::$(composer config cache-files-dir)"

            -   name: Cache Composer's dependencies
                uses: actions/cache@v2.1.4
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: php-composer-dependencies-cache

            -   name: Fix Symfony version
                run: |
                    composer req symfony/flex --no-scripts
                    composer config extra.symfony.require "${{ matrix.symfony }}"

            -   name: Remove Rector
                run: |
                    composer rem rector/rector --dev

            -   name: Install Composer deps
                run: |
                    composer update ${{ matrix.composer-flags }} --no-interaction --no-scripts
                    composer bin phan update
                    composer bin phpunit update

            -   name: Run Phan
                run: |
                    ./vendor/bin/phan --no-progress-bar --dead-code-detection --load-baseline .baseline-phan.php
